"""empty message

Revision ID: 4ce17b09a939
Revises: f512acc786d2
Create Date: 2024-05-09 12:12:19.601937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce17b09a939'
down_revision = 'f512acc786d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_fact', schema=None) as batch_op:
        batch_op.alter_column('fact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_fact', schema=None) as batch_op:
        batch_op.alter_column('fact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
