"""empty message

Revision ID: 7163f9f14800
Revises: 14c1d6a93342
Create Date: 2024-05-02 14:11:36.132709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7163f9f14800'
down_revision = '14c1d6a93342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_fact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_fact', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
